"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, FileCheck2, Fingerprint, ShieldCheck, Wallet, Play, Maximize2, Check, Layers, Link2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
const slides = [
 {tag:'01 / 产品价值',title:'从一份标书，走向一份共同确认的约定。',text:'MonadSpark 面向投标企业，把标书、合同与双方确认关联到同一条记录。已有 AI 负责编标，我们聚焦后续的版本确认。',steps:['已有 AI 编制标书','关联最终版合同','双方确认同一版本'],note:'贯穿示例：虚构的设备供应项目，不使用真实企业资料。',icon:Layers},
 {tag:'02 / 链上账号',title:'用自己的钱包，代表自己的链上账号。',text:'双方各自连接钱包，在 Monad 测试网注册。甲方钱包地址就是本次指定签署方的账号标识。',steps:['连接自己的钱包','切换 Monad 测试网','确认账号注册'],note:'密钥留在各自钱包中；钱包地址不等于企业身份认证。',icon:Wallet},
 {tag:'03 / 准备文件',title:'留下文件指纹，原文由你保管。',text:'选择最终版标书与合同，浏览器分别计算校验码。可以把它理解成文件的数字指纹，用于判断内容是否发生改变。',steps:['选择最终版标书','选择关联的合同','本地计算两份指纹'],note:'设计中只把文件指纹写入公开链，不把标书和合同原文放上去。',icon:Fingerprint},
 {tag:'04 / 发起签署',title:'明确签什么，也明确由谁签。',text:'投标企业填写甲方钱包地址，检查文件版本，然后在钱包中确认发起。链上记录固定两份指纹及双方地址。',steps:['检查文件与甲方地址','钱包确认发起','把链接与原件发送给甲方'],note:'原件需要通过双方认可的安全渠道发送；签署链接不包含文件原文。',icon:Link2},
 {tag:'05 / 甲方确认',title:'先核对同一份文件，再确认签署。',text:'甲方打开链接、连接指定钱包、导入收到的原件。只有文件指纹匹配，才能继续确认签署。',steps:['导入收到的两份文件','对照链上指纹','阅读后确认签署'],note:'计划规则：其他账号不能代签；同一记录不能重复签署。',icon:FileCheck2},
 {tag:'06 / 后续核验',title:'合同改了一个字，也要重新确认版本。',text:'再次导入文件，对比记录中的原始指纹。如果合同金额被修改，核验结果应显示不一致，原签署记录不能用于新版本。',steps:['选择需要核验的文件','读取原签署记录','判断一致或已发生变化'],note:'自检：把示例合同中的金额改掉，应该通过核验吗？不应该。',icon:ShieldCheck},
];
export default function Page(){
 const [tab,setTab]=useState('overview'); const [index,setIndex]=useState(0); const [hint,setHint]=useState(''); const deck=useRef<HTMLDivElement>(null); const touch=useRef<{x:number,y:number}|null>(null);
 const go=(n:number)=>setIndex(Math.max(0,Math.min(slides.length-1,n)));
 useEffect(()=>{if(tab!=='demo')return; const key=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(el.closest('button,input,textarea,select,[role="tab"],[contenteditable="true"]'))return;if(['ArrowRight','ArrowLeft','Home','End',' '].includes(e.key)){e.preventDefault();setIndex(i=>e.key==='Home'?0:e.key==='End'?slides.length-1:Math.max(0,Math.min(slides.length-1,i+(e.key==='ArrowLeft'?-1:1))));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[tab]);
 const s=slides[index]; const Icon=s.icon;
 return <div className="marketing"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><header className="m-header"><a className="m-brand" href="/" aria-label="MonadSpark 首页"><FileCheck2/>MonadSpark<span>文档签署</span></a><TabsList aria-label="网站内容" className="m-tabs"><TabsTrigger value="overview">产品介绍</TabsTrigger><TabsTrigger value="demo"><Play size={14}/>产品演示</TabsTrigger></TabsList><a className="m-stage" href="/workspace">进入交互 Demo →</a></header>
 <TabsContent value="overview"><main><section className="m-hero"><div><div className="m-kicker">DOCUMENTS. AGREED.</div><h1>标书到合同，<br/>让约定<span>有据可查。</span></h1><p className="m-lead">为投标企业设计的文档签署空间。<br/>关联文件、邀请甲方、核验版本，<br/>用 Monad 记录双方确认的那一份。</p><div className="m-actions"><a href="/workspace" className="demo-entry">体验签署 Demo →</a><Button onClick={()=>setTab('demo')}>了解如何使用 <ArrowRight/></Button><a href="#features">探索产品功能 <span>↓</span></a></div><p className="m-caption">当前提供产品流程演示，真实链上签署正在开发。</p></div><div className="document-scene" aria-label="示意：标书与合同通过数字指纹关联到同一签署记录"><div className="scene-top"><span>一份文件包 · 一次共同确认</span><span>流程示意</span></div><div className="paper back-paper"><FileCheck2/><span>投标文件</span><b>设备供应方案</b><div className="paper-lines"/></div><div className="paper front-paper"><div className="paper-heading"><FileCheck2/><span>CONTRACT / 001</span></div><h3>设备供应合同</h3><p>关联标书 · 最终确认版本</p><div className="paper-lines"/><div className="signature"><span>投标企业</span><span>指定甲方</span></div><div className="fingerprint"><Fingerprint/><span>文件指纹关联<br/><small>原文保留在你的手中</small></span></div></div><div className="chain-chip"><Layers size={19}/><div>Monad<span>链上记录 · 规划能力</span></div><Link2 size={18}/></div></div></section>
 <section className="m-value-strip"><span>面向投标企业</span><span>衔接已有 AI 编标</span><span>文件原文不上公开链</span><span>基于 Monad 测试网设计</span></section>
 <section id="features" className="m-section"><div className="section-heading"><div><div className="m-kicker">从版本到确认</div><h2>把签署前后的三件事，理清楚。</h2></div><p>知道签的是哪份文件，<br/>由谁确认，以及后来有没有改动。</p></div><div className="feature-grid">{[{icon:Layers,n:'01',title:'标书与合同，一起关联',text:'把两份最终文件作为一个文件包，减少标书、合同版本各自流转带来的混淆。'},{icon:Wallet,n:'02',title:'指定甲方，分别确认',text:'由发起方指定签署钱包，双方用各自账号确认，保留清晰的参与方记录。'},{icon:Fingerprint,n:'03',title:'再次核验，识别改动',text:'用文件指纹比对版本。文件改变后，需要重新确认，不能沿用旧版签署记录。'}].map(f=><article key={f.n}><div className="feature-top"><f.icon/><span>{f.n}</span></div><h3>{f.title}</h3><p>{f.text}</p><span className="planned">规划能力</span></article>)}</div></section>
 <section className="m-walkthrough"><div><div className="m-kicker">HOW IT WORKS</div><h2>三分钟，看懂一次签署。</h2><p>从账号准备到文件核验，跟着一个虚构项目走一遍。</p></div><Button onClick={()=>{setIndex(0);setTab('demo');window.scrollTo(0,0)}}><Play/>开始产品演示</Button></section>
 <section className="m-section m-faq"><h2>开始前，你可能想知道</h2>{[['会重新开发 AI 编标吗？','不会。我们衔接你已有的 AI 编标成果，当前聚焦文件关联、账号、签署和核验。'],['合同原文会公开吗？','设计中由浏览器在本地计算指纹，链上只记录指纹及签署信息。原件由双方自行保管和安全传递。'],['现在能用于真实企业签约吗？','当前是比赛实验原型，链上功能尚未完成。企业正式使用还需要身份认证、授权管理及相应电子签约方案。']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section></main></TabsContent>
 <TabsContent value="demo"><div ref={deck} className="deck" onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)go(index+(dx<0?1:-1));touch.current=null;}}><div className="deck-top"><span>MONADSPARK / 产品演示</span><Button variant="ghost" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await deck.current?.requestFullscreen();setHint('');}catch{setHint('当前浏览器不支持全屏，可继续在此翻页。')}}}><Maximize2 size={16}/>全屏</Button></div><div className="slide" key={index} aria-live="polite" tabIndex={0}><div className="slide-copy"><div className="m-kicker">{s.tag}</div><h2>{s.title}</h2><p>{s.text}</p><div className="slide-note">{s.note}</div></div><div className="slide-visual"><Icon className="slide-icon"/><div className="slide-flow">{s.steps.map((v,i)=><div key={v}><span>{i+1}</span><strong>{v}</strong><Check size={16}/></div>)}</div><span className="slide-label">使用流程示意 · 非真实交易结果</span></div></div><div className="deck-bottom"><div className="slide-jumps" aria-label="选择演示页">{slides.map((v,i)=><button key={v.tag} aria-label={v.tag} aria-current={i===index?'step':undefined} onClick={()=>go(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><div className="deck-controls"><Button variant="ghost" aria-label="上一页" disabled={index===0} onClick={()=>go(index-1)}><ArrowLeft/></Button><span>{index+1} / {slides.length}</span><Button variant="ghost" aria-label="下一页" disabled={index===slides.length-1} onClick={()=>go(index+1)}><ArrowRight/></Button></div></div><div className="deck-progress"><span style={{width:`${(index+1)/slides.length*100}%`}}/></div><p className="deck-help" role="status">{hint||'方向键翻页 · 手机左右滑动 · 点击页码跳转'}</p></div></TabsContent>
 </Tabs><footer className="m-footer"><a className="m-brand" href="/">MonadSpark</a><span>比赛实验项目 · 当前为产品介绍与交互演示</span><span>目标域名 captionrewrite.com · 尚未绑定</span></footer></div>
}
